#
# ~/.bashrc
#

# Installin Base packages
pacman -S --needed amd-ucode archinstall arch-install-scripts b43-fwcutter base-devel bash-completion bind-tools brltty broadcom-wl btrfs-progs clonezilla cloud-init crda darkhttpd ddrescue dex dhclient dhcpcd diffutils dmraid dnsmasq dosfstools edk2-shell efibootmgr espeakup ethtool exfatprogs f2fs-tools fatresize fsarchiver gnu-netcat gpart gpm gptfdisk grml-zsh-config grub hdparm ipw2100-fw pw2200-fw irssi iwd jfsutils kitty-terminfo lftp libxinerama linux-headers linux-atm linux-firmware livecd-sounds lsscsi lvm2 lynx make man-db man-pages mc mdadm memtest86+ mkinitcpio mkinitcpio-archiso mkinitcpio-nfs-utils mkinitcpio-openswap modemmanager mtools nbd ndisc6 networkmanager network-manager-applet nfs-utils nilfs-utils nmap ntfs-3g nvme-cli openconnect openssh openvpn os-prober partclone parted partimage ppp pptpclient reflector reiserfsprogs rp-pppoe rsync rxvt-unicode-terminfo sddm sdparm sg3_utils smartmontools sof-firmware squashfs-tools sudo syslinux systemd-resolvconf tcpdump terminus-font termite-terminfo testdisk tmux udftools usb_modeswitch usbmuxd usbutils vpnc wireless-regdb wireless_tools wpa_supplicant wvdial xdg-user-dirs xfsprogs xl2tpd xorg-xkill xorg-server xorg-apps xorg-xinit  xterm xorg-xrdb zsh
Sleep 5
# Installin Extra packages
pacman -S --needed alsa-firmware alsa-plugins alsa-lib alsa-utils gst-libav gst-plugins-bad gst-plugins-base gst-plugins-good gst-plugins-ugly gstreamer libdvdcss pulseaudio pulseaudio-alsa blueberry bluez bluez-libs bluez-utils pulseaudio-bluetooth avahi nss-mdns mobile-broadband-provider-info modemmanager net-tools networkmanager-openconnect networkmanager-openvpn networkmanager-pptp networkmanager-vpnc openresolv rate-arch-mirrors-bin smbclient traceroute gvfs gvfs-afc gvfs-gphoto2 gvfs-mtp gvfs-nfs gvfs-smb mtpfs udiskie udisks2 
Sleep 5
# Installin Extra+ packages
pacman -S --needed feh gmrun imagemagick numlockx scrot jq lm_sensors adobe-source-sans-pro-fonts awesome-terminal-fonts noto-fonts ttf-dejavu ttf-droid ttf-hack ttf-roboto ttf-ubuntu-font-family arc-icon-theme papirus-icon-theme arandr asciinema assimp autofs baobab boost cblas cifs-utils cmake dconf-editor dex dmidecode exfat-utils expac extra-cmake-modules file-roller fuse2 fuse3 fuseiso git glib2-docs gparted graphviz gtest gtk-doc gts hardinfo hddtemp grsync intltool iw jsoncpp libmtp laptop-detect lhasa lsb-release lzop meson mlocate netpbm ninja nmon nodejs node-gyp npm oniguruma p7zip perl-xml-parser pkgstats playerctl polkit dbus-python python2-pyxdg rxvt-unicode speedtest-cli tree gufw qt5-3d rhash s3fs-fuse semver snapper sshfs unace unrar unzip vala vnstat w3m webkit2gtk wmctrl xapps xdo xdotool xfce4-dev-tools zenity zip python-cffi python-numpy python-docopt python-pyaudio python-anytree python-pygments python-websockets archey3 appstream archiso bleachbit expac gufw inetutils lolcat lshw neofetch synapse sysprof yad yakuake
Sleep 5
# Installin Dependencies
pacman -S --needed upower kcoreaddons kconfig ki18n kservice kwidgetsaddons kpmcore boost-libs libpwquality squashfs-tools plasma-framework hwinfo qt5-xmlpatterns go packagekit-qt5 pacman-contrib partitionmanager kde-gtk-config sddm-kcm cryfs encfs gocryptfs
